# version: "3.9"

# services:
#   db:
#     image: mysql:8
#     container_name: mysql2
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#       MYSQL_DATABASE: ${DATABASE}
#     ports:
#       - "3307:3306"      # kívül 3307, konténerben 3306
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - backend

#   app:
#     build: .
#     container_name: backstage-app
#     restart: always
#     env_file:
#       - .env
#     ports:
#       - "3000:3000"
#     depends_on:
#       - db
#     networks:
#       - backend

# networks:
#   backend:

# volumes:
#   mysql_data: